version: '3.3'
services:
  node:
    container_name: container_node
    image: 'node:latest'
    working_dir: /home/node/app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/node/app'
    links:
      - mongo
    networks:
      - my-network
  mongo:
    container_name: container_mongo
    image: mongo
    # working_dir: /database
    # command:
    #   - /bin/sh
    #   - '-c'
    #   - 'bash database.sh db_feedback_ipssi'
      # - 'db.collections.users.save({"password": "password", "email": "admin@admin.com", "last_name": "adminlastname", "first_name": "adminfirstname", "role": "admin"})'
    ports:
      - "27017:27017"
    # volumes:
    #   - './database:/database'
    networks:
      - my-network
networks:
  my-network:
    driver: bridge