version: '3.3'
services:
  node:
    container_name: container_node
    image: 'node:latest'
    working_dir: /home/node/app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/node/app'
    links:
      - mongo
    networks:
      - my-network
  mongo:
    container_name: container_mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge